### ISSUE TITLE
Dimension mismatch in spsolve()

### ISSUE THREAD

**Issue by Tongdongq** [spietz/2DFiniteVolume#1]
$ python UniformFlow.py 
Traceback (most recent call last):
  File "UniformFlow.py", line 53, in <module>
    T = spsolve(A, s.reshape(1, n**2, order='F')).reshape(n,n, order='F')
  File "/home/tdqiu/.local/lib/python2.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 157, in spsolve
    % (A.shape, b.shape[0]))
ValueError: matrix - rhs dimension mismatch ((10000, 10000) - 1)

Fixed by changing line 53 to 'T = spsolve(A, s.ravel()).reshape(n, n, order='F')' and line 104 to 'plt.show(block=True)'.

**Comment by spietz** [comment]
Hi, thanks for your inputs to getting codes up and running again!
Note that the code is a port of an old matlab-code, so arrays must be flattened using column-major order: E.g. flattening the righthandside use s.ravel(order="F") or s.reshape(n**2,order="F") to get correct results.

**Comment by spietz** [comment]
I dont think plt.show or fig.show is neccesary using plt.ion() .
I've updated the repository now.
